### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by ricsmania** [Telerik-Verified-Plugins/Couchbase-Lite-DemoApp#3]
I'm trying to run the demo on Android, but both on an emulator and a physical device (Galaxy S6) I get this error when opening the application:

Unfortunately, Couchbase Lite plugin demo has stopped.

Tried using Telerik's web client and also the desktop IDE.

**Comment by EddyVerbruggen** [comment]
I'm afraid the demo app which is merely a copy of [this repo](https://github.com/couchbaselabs/TodoLite-PhoneGap) has issues with more recent Android versions.

Can you perhaps do a `adb logcat` and attach the log?

**Comment by ricsmania** [comment]
@EddyVerbruggen after some trial and error I got it to work by changing the Cordova version to 3.8.0. Strangely now it works even after going back to 4.0. I don't know what was happening before.
